[project]
name = "uv-workspace-packaging-example"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "commonlib",
    "app0",
    "app0/workspace:",
]
